- name: Create psk dir
  file:
    path: "{{ setting_psk_path }}"
    state: directory

- name: Upload psk, conf, parameter files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "psk_files/key_{{ psk_filename }}",   dest: "{{ setting_psk_path }}/zabbix_agentd.psk" }
    - { src: "zabbix_agentd.conf",                 dest: "/etc/zabbix" }
