- name: Create psk on zabbix-master
  shell: "/usr/bin/psktool -u {{ psk_identity }} -p {{ psk_filename }}"
  args:
    chdir: "{{ psk_path }}"
    creates: "{{ psk_path }}/{{ psk_filename }}"
  become: yes

- name: Download psk
  fetch:
    src: "{{ psk_path }}/{{ psk_filename }}"
    dest: "psk_files/full_{{ psk_filename }}"
    flat: yes
  become: yes

- name: Create key for psk
  local_action:
    module: shell
    args: "cut -d: -f2 psk_files/full_{{ psk_filename }} > psk_files/key_{{ psk_filename }}"
    creates: "psk_files/key_{{ psk_filename }}"
