- name: Install python-apt
  apt:
    name: python-apt
    update_cache: yes
  tags:
    - standby

- name: Get repo
  get_url:
    url: "{{ zabbix_repository }}"
    dest: /usr/local/src
  register: dl_result
  until: dl_result is succeeded
  retries: 3
  delay: 5

- name: Install Zabbix-SIA
  apt:
    deb: "/usr/local/src/{{ zabbix_release_file }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install zabbix-agent
  apt:
    name: "zabbix-agent"
    #name: "zabbix-agent=1:{{ zabbix_version }}.0rc3-1+stretch"
    #name: "zabbix-agent=1:4.0.0rc3-1+stretch"
    update_cache: yes
