## ansible_os_family - ansible_distribution
##  Debian           - Debian
##  Debian           - Ubuntu
##  RedHat           - CentOS
##  RedHat           - Amazon

- include_vars: "{{ ansible_os_family }}"

- include_tasks: "{{ ansible_os_family }}.yml"
  tags: standby
  become: yes
